modLoader="javafml"
loaderVersion="[47,)"
license="MIT"
issueTrackerURL=""

[[mods]]
modId="andymod"
version="1.0.1"
logoFile="logo.png"
displayName="Andy Mod"
displayURL="https://ma4z.pages.dev"
credits="gwidoniusz99, ma4z"
authors="ma4z, gwidoniusz99"
description='''
a dude who like u
'''
[[dependencies.andymod]]
modId="forge"
mandatory=true
versionRange="[47,)"
ordering="NONE"
side="BOTH"

[[dependencies.andymod]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1]"
ordering="NONE"
side="BOTH"

[[dependencies.andymod]]
modId="geckolib"
mandatory=true
versionRange="[4.0.0,)"
ordering="NONE"
side="BOTH"